[supabase]
url = "https://luhyiqhlknmhpvramiib.supabase.co"
service_role_key = "sb_secret_WZF3uy3A62EUDJyyaAaG6A_d1iYmFhA"
storage_bucket = "marksheets"

[srms]
owner_id = "9767781844"
owner_password = "AAaaBBbb11$"
